// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCwIla2NWDGRi3P0T88pBSm6a87uOlq88',
    appId: '1:693624745919:web:5692181f14d29af9da7b0a',
    messagingSenderId: '693624745919',
    projectId: 'shopink-c705a',
    authDomain: 'shopink-c705a.firebaseapp.com',
    storageBucket: 'shopink-c705a.appspot.com',
    measurementId: 'G-TJLNVQKQX6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdYLpSRu8Rpotpzt-QNX1jGxnPrqIDmRY',
    appId: '1:693624745919:android:347e03480fb8f3ddda7b0a',
    messagingSenderId: '693624745919',
    projectId: 'shopink-c705a',
    storageBucket: 'shopink-c705a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtOoY0GVxZNXKWDr98wBSS-eEEkug-QJ0',
    appId: '1:693624745919:ios:93bde5339752f986da7b0a',
    messagingSenderId: '693624745919',
    projectId: 'shopink-c705a',
    storageBucket: 'shopink-c705a.appspot.com',
    iosBundleId: 'com.example.shopink',
  );
}
